### ISSUE TITLE
Most of the examples do not work.

### ISSUE THREAD

**Issue by phpzero** [go-ole/go-ole#15]
Most of the examples do not work.

.../sample/excel/excel.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4210e3]

goroutine 1 [running]:
ole.getIDsOfName(0x0, 0x3b1db8, 0x1, 0x1, 0xc0800000c8, ...)
	C:/Work/test/src/ole/idispatch.go:74 +0x163
ole.(*IDispatch).GetIDsOfName(0x0, 0x3b1db8, 0x1, 0x1, 0x0, ...)
	C:/Work/test/src/ole/idispatch.go:41 +0x81
ole/oleutil.PutProperty(0x0, 0x4bfdc0, 0x5, 0x3b1e48, 0x1, ...)
	C:/Work/test/src/ole/oleutil/oleutil.go:76 +0xb2
main.main()
	C:/Work/test/src/ole/example/excel/excel.go:18 +0x3b4
Error: process exited with code 2.
```

**Comment by millergarym** [comment]
Same issue, but maybe with a bit more information.
This has been working for me, until I 'crashed' Excel and since then "Cells" and some other calls have stopped working. I am trying to communicate with an Add-In (I am maintaining) in Excel. I was trying to using Application.Run( "MyMacro", "Param" ). This was working, but stopped at the same time as "Cells".

Is it possible that CreateObject and GetObject are getting a different COM interface to Excel?
The thing about "Cells" is that it is the default method, where Range is not a default method.

Thanks
Gary

os: windows 7 pro sp 1
go version: 1.3.3 windows/x86
Excel version: Excel 2007 32bit
cell := oleutil.MustGetProperty(worksheet, "Cells", 1, 1).ToIDispatch()
cell == !nil

**Comment by jacobsantos** [comment]
I am hoping #24 will solve this problem. Examples will be updated to use Test COM Sever instead.

**Comment by jacobsantos** [comment]
Support issue it seems like. Future examples will use go-ole Test COM server instead of depending on specific programs that require purchase.

**Comment by jacobsantos** [comment]
I'm hoping to find a free or community version of Excel comes out that allows for testing this to ensure it isn't a library issue.
