### ISSUE TITLE
Go Generate from Type Information

### ISSUE THREAD

**Issue by jacobsantos** [go-ole/go-ole#59]
**Edit:** This has been updated to match the information below in https://github.com/mattn/go-ole/issues/59#issuecomment-91078865.

**The tool will require either Windows or WINE and the COM server must be registered.**

This has been on my wish list for a long time and with Go Generate tool, I think it could finally be achieved within a reasonable amount of time.

The idea is to generate the Go code based on the COM type information. This must include helper functions that call into the Go OLE library functions (helpers or core) for the programmer. This could also include other Go language features to help with the process of passing data around.

So the tool would generate all or most of the code required to interop with COM or OLE with the command:

 `go generate`

with the comment:

 `//go:generate [ole|com|???] -o something.go -i [com-uuid|registered name]`

The `-t` defines how the interface or class methods and properties are invoked.
 * `-t direct` - Casts the COM pointer to Go structure with methods calling out to pointers.
    
    This is useful for outputting internal COM interfaces or other raw interfaces. This follows the format and standard of the current interface packages.
    
    The goal is to be able to output the current hand coded COM interfaces using the Go generate tool. This should provide improvements that are made to the go generate tool, to the internal packages. As well as support more interfaces without having to hand code each one.
 * `-t idispatch` - Uses the IDispatch COM interface to invoke properties and methods using helpers.
    
    This will create a Go structure with type methods that will invoke based on the arguments. oleutil might be rolled back into the main library and functions used in the generation of the object and its methods.

## Paradigm

The output should always be a structure type with type methods that invoke based on parameters. How the developer uses the structure will be up to the developer. Technically, the current paradigms are both procedural and object-oriented. The functions are what actually implement the calls into the COM interface or object.

The type methods use the functions and pass the necessary data and parameters. The purpose is to allow for other structures and their type methods to use the existing functions without having to duplicate any code other than the type method structure.

For example, every COM interface inherits from `IUnknown` interface and so each structure has type methods that duplicate the definition found in the `iunknown` package. Technically, every interface already has these type methods. The reason they are explicitly defined is for documentation and for testing whether the design is the best way to output the code. *Testing might remove the explicit type methods from additional structures.*

**This needs to also output the COM client initialization, which is then used throughout the generated code.**

## Additional Go Tool Features

The COM or OLE Go tool should also be able to output current COM interfaces and objects along with type information in either human readable or JSON format. Should also have a search feature to quickly filter results. This will hopefully allow for developers to quickly find whether the COM object is registered and retrieve additional information before generating code.

**Comment by jacobsantos** [comment]
Well, should also generate some *_test.go files as well, if reasonably possible. Most likely based on an existing template.

**Comment by mgspross** [comment]
That sounds difficult. IDL and variations like ODL are fairly complicated in terms of parsing, from what I know about them. The language grammar is a weird superset of a subset of C's grammar. ;-)

I've used Microsoft's Type Information Library (`tlbinf32.dll`) in the past to read interface information from COM libraries - it's a COM DLL that can read type libraries in binary form, so it can load interface information directly from COM binaries (i.e. DLL's and OCX's), as well as from compiled type library (TLB) files.

The library's API is a little difficult to deal with, and it isn't documented very well, although there are some resources online, such as this Dr. Dobb's article: 

* [Accessing Type Libraries from VB](http://www.drdobbs.com/accessing-type-libraries-from-vb/184416565)

...and this MSN Magazine article:

* [Visual Basic: Inspect COM Components Using the TypeLib Information Object Library](https://msdn.microsoft.com/en-us/magazine/bb985086.aspx)

Since `tlbinf32.dll` can read the interface in compiled form, this also means you don't need to have the original IDL in order to generate the code in Go. Instead, you need a TLB file for the COM library, or, in most cases, the COM DLL or OCX file itself, since the type library is usually embedded in the binary file.

You can also load type libraries using the LIBID (the GUID for the type library) and the type library version you want, which is really mostly useful for cases where one DLL contains type libraries for multiple COM API's (which seems rare).

`tlbinf32.dll` is also redistributable, so it could be packaged with a helper program that actually generates the Go code.

We could write the code generation tool in C#, VB.NET, or even VB6 (!), because we can easily use `tlbinf32.dll` from any of these. If we don't want to ship a tool written in another language, we could write an initial implementation of the generator in one of those languages, and then run `tlbinf32.dll` through the tool to generate a pure Go implementation of a `tlbinf32.dll` wrapper, which in turn could be used to write a generator in Go with no other languages needed.

The catch is that `tlbinf32.dll` would need to distributed and registered on end-user machines for this approach to work, but using this library would keep us from having to implement our own IDL/ODL parser from scratch, which could save time and effort.

**Comment by jacobsantos** [comment]
Excellent. I think I am going to switch to this instead using the information you gave me. Having a tool that generates Go COM code would be much better and allow me to get some practice with C#. I'm still reading through the .NET COM book, but it is slow.

I like your idea of having C# program, but just have the C# program use the `tlbinf32.dll` to get the type information and then convert it to JSON. That way the go tool would be able to call into the C# program, get the JSON and then generate the Go code for output. The primary reason for this is that Go already has Go language libraries that should reduce the work and hopefully allow generating updated Go code with minimal work.

I'd have to look at how the other go generate tools work, but I'm hoping that it is almost as simple as generating the AST nodes and passing it to the library function. If I remember correctly, that might be close to correct with a few nuances I'm forgetting or misunderstanding from the library's function descriptions.

To be clear, I would rather have a system where if you are using Go 1.2, that Go 1.2 code is generated and if you are on Go 1.x that 1.x code is generated. And so on for 2.x and X.x, if at all possible.

The other go generate tools either include or require external tools, so even if the C# program isn't included, part of the process would be to download the tool. Going to need to check with how this is going to work with Linux or if it will work with Linux. 


Is it possible to download `tlbinf32.dll` and register it as part of the tool process? Or would it be better to include it in the repository? The reason I ask is whether license would restrict having it in the package.

**Comment by jacobsantos** [comment]
Having this tool should actually allow for generating the COM code for the COM test server.

**Comment by mgspross** [comment]
> Is it possible to download `tlbinf32.dll` and register it as part of the tool process? Or would it be better to include it in the repository? The reason I ask is whether license would restrict having it in the package.

I don't think Microsoft has a public download link for the file. It was originally shipped with VB6. I'm not sure if it is included with Visual Studio/.NET.

We use it in one of our legacy applications where I work, and the version we use works on Windows XP and all later versions of Windows, and I believe it would also work on Windows 2000.

My understanding is that the library is not officially supported by Microsoft, but the licensing allows you to redistribute it without any restrictions.

The `REDIST.txt` file that ships with VB6 installation lists `tlbinf32.dll` as **REDISTRIBUTABLE CODE - Standard**, for example, which seems to be the least-restrictive category for the files included with VB6.

So, I think it would be fine to either include the file in the repository or host it publicly somewhere. If we decide to add an explicit license to `go-ole`, we might have to host it outside of the repository, depending on what license we would choose. 

Right now, without an explicit `LICENSE` file, there isn't any restriction on putting closed-source binaries in the repository, but if we were to use GPLv3, that would change, because `tlbinf32.dll` doesn't meet their definition of "system library."

**Comment by jacobsantos** [comment]
@mgspross Doing some research, you can just inspect using `ITypeInfo` through COM. This will read the TypeLibrary file, if it exists, and allow for you to reflect on the methods and properties. The API for doing so, seems to be very convoluted, so the implementation could be pretty involved.

I think for the moment, I'm going to go with this, since, I think `tlbinf32.dll` will essentially be giving the same information. I haven't been able to check the API of `tlbinf32.dll`, or if it would be easier than `ITypeInfo`.

I think I'm going to have to still do some of the work on the library, but I know what I'm going to try `ITypeInfo` first. If the tool's only dependency is COM, then it won't require a separate Windows / WINE application. I am hoping that just sticking with the COM library will provide enough support to complete this project. 

I have a feeling that it won't solve 100% of all of the cases. I think, even if it solved 50%, then that might be good enough of a start. The tool could always be extended later to support more use cases. Doing so would be outside the scope of my current ability.

I am still thinking of allowing for JSON or YAML or both formatted file for providing basic type information in the instance that no type library is provided or registered. The other reason for still supporting the JSON or YAML or both, is so that it would provide the user the choice of which parts of the API to output as Go code.

Also, if this could be done in the Go tool, then the Go tool could also output the JSON or YAML or both formatted file to allow for the developer to choose which parts of the API are outputted as Go code.

If `ITypeInfo` provides a solution, then I think at a future date whether or not to add `tlbinf32.dll` and other reflection techniques to the tool should be evaluated. The resources I have seem to suggest that most COM APIs will come with a TypeLibrary, but I'm not sure of the accuracy of that claim.

**Comment by mgspross** [comment]
I would assume that `tlbinf32.dll` uses `ITypeInfo` and other related interfaces internally - using `tlbinf32.dll` directly occurred to me first because it's the easiest way to use that functionality from languages that support COM. I'm fairly certain `tlbinf32.dll` is just a wrapper for `ITypeLib`, `ITypeInfo`, and other related interfaces. I'll refer to the `ITypeInfo` API the "native API" to differentiate it from `tlbinf32.dll` in this post.

In the native API, it looks like `ITypeLib` is the top-level interface - you can then get the `ITypeInfo` for each type in a type library through that interface.

Here are some reference articles:
* **[Type Description Interfaces](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221442(v=vs.85).aspx)**: This describes the main interfaces in the native API
* **[Type Description Functions](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221342(v=vs.85).aspx)**: This describes the functions for accessing the native API interfaces, such as the `LoadTypeLib`, `LoadTypeLibEx`, and `LoadRegTypeLib` functions, which can be used to retrieve an `ITypeLib` instance.

`tlbin32.dll` exposes a similar API, but with different names for things, and in a way that would be a bit more compact perhaps, because it's wrapping some of the more complex functions and functionality in the native API in "nicer" patterns, like using collections for lists instead of list-accessor functions.

That said, I agree using the native API seems preferable, since it removes the dependency on `tlbinf32.dll`.

The native API is still a COM API, however, so it would only work from Windows (and would probably work in WINE too).

The main difference is that the native API is available as part of COM/OLE, so no extra files need to be distributed or registered.

Lastly, I can tell you the `tlbinf32.dll` is pretty convoluted too, as I've used it many times myself. I've actually never used the native API directly, but as I said, I tend to agree it would probably be the better choice in this situation.

**Comment by jacobsantos** [comment]
I have been looking at those. Right. So I have all of the information I need now. I'm kind of excited to finally work on this after doing all of the research. You did provide the final piece for me with the `ITypeLib`.

I was wondering how to actually get all of the interfaces in the Type Library. `ITypeInfo` does not give this, so that is why I was confused.

I'm going to have to spend some time mocking up some code testing out how to get the information. It does seem however that it shouldn't be that difficult, since `GetTypeInfo()` gives you a `ITypeInfo` object, which you can then get all of the methods and properties.

I will need to do some restructuring of the code first. I think putting this in its own package would make sense, given that I don't think many will require it. I also don't want the tool to require the complete COM package.

**Comment by jacobsantos** [comment]
This have moved to another repository.
